# This is a basic workflow to help you get started with Actions
# Base addition of github action, to only run when PR merged to develop
name: Prepublish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    types:
      - closed
    branches:
      - 'develop'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: github.event.pull_request.merged == true
    env:
      NPM_TOKEN: ${{secrets.NPM_TOKEN}}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'

    # Update develop for minor prerelease
    - name: Create minor prerelease
      if: startsWith(github.head_ref, 'feature/') == true
      run: |
        npm ci
        npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        git config --global user.name 'David Sornberger'
        git config --global user.email 'snoretrain@users.noreply.github.com'
        npm version preminor --preid=beta
        git push --follow-tags
        npm publish --tag beta
    
    # Update develop for patch prerelease
    - name: Create patch prerelease
      if: startsWith(github.head_ref, 'patch/') == true || startsWith(github.head_ref, 'dependabot/') == true
      run: |
        npm ci
        npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        git config --global user.name 'David Sornberger'
        git config --global user.email 'snoretrain@users.noreply.github.com'
        npm version prepatch --preid=beta
        git push --follow-tags
        npm publish --tag beta
