# This is a basic workflow to help you get started with Actions
# Base addition of github action, to only run when PR merged to develop
name: Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - 'master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with:
        node-version: '14'

    # Create release for pre
    - name: Create full release for prerelease
      run: |
        npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        git pull origin develop
        git pull origin master
        git checkout master
        npm version patch
        git push --follow-tags
        git pull origin master
        git checkout develop
        git merge --no-ff master
        git push origin develop
        npm publish
